/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
static yyconst short int yy_accept[219] =
    {   0,
        0,    0,   90,   88,    2,    1,   28,   88,   23,   25,
       88,   12,   13,   21,   19,   52,   20,   18,   22,   81,
       81,   15,   14,   30,   29,   31,   17,   78,   78,    8,
       10,   24,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,    4,   26,    6,   27,    2,   45,
        0,   86,    0,   36,    7,   48,   38,    0,   84,    0,
       34,   50,   32,   51,   33,   53,    0,   82,    3,   35,
       82,   80,   81,    0,   81,   81,    0,   11,    5,    9,
       40,   46,   44,   47,   41,   78,    0,    0,   37,   78,
       78,   78,   78,   78,   78,   61,   78,   78,   78,   78,

       78,   78,   68,   78,   78,   78,   78,   78,   78,   39,
       49,    0,   86,    0,    0,   84,    0,   16,    0,   82,
       80,   80,    0,   83,   81,   81,   79,   42,   43,    0,
       87,    0,    0,   85,    0,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   67,   78,   69,   78,
       78,   78,   78,   78,   78,   78,    0,   82,   80,   80,
       83,   79,   79,    0,   87,    0,    0,   85,    0,   54,
       78,   56,   57,   78,   78,   78,   78,   63,   64,   78,
       78,   77,   78,   78,   78,   78,   78,   75,   78,   79,
       79,   55,   58,   78,   78,   78,   78,   66,   78,   78,

       72,   78,   78,   76,   78,   78,   62,   65,   78,   71,
       73,   74,   78,   60,   78,   59,   70,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   29,   29,   51,   52,   53,   54,   55,   56,   57,
       29,   58,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    3,    3,
        3,    3,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[229] =
    {   0,
        0,    0,  358,  359,  355,  359,  333,   58,   41,   59,
       59,  359,  359,  332,   56,  359,   57,   55,   64,   79,
       59,  330,  359,   63,  330,   65,  359,    0,   94,  359,
      359,  329,  297,  299,   63,   54,   65,   58,  299,   75,
      307,   74,  297,  302,  359,   55,  359,  359,  343,  359,
       96,  359,  118,  359,  359,  359,  359,   95,  359,  124,
      359,  359,  359,  359,  359,  359,  329,  120,  359,  359,
      127,  160,    0,  180,   97,   95,    0,  359,  359,  359,
      320,  359,  359,  359,  319,    0,  126,  132,  359,  288,
      299,  287,  301,  288,  294,  281,  282,  279,  279,  281,

      279,  276,    0,  275,  100,  277,   91,  281,  280,  359,
      359,  130,  136,  168,  148,  151,  178,  359,  191,  359,
      134,  133,  198,  201,  359,  359,  191,  359,  359,  179,
      359,  190,  192,  359,  203,  274,  286,  281,  270,  175,
      283,  281,  277,  269,  275,  278,    0,  264,    0,  268,
      258,  260,  261,  268,  268,  260,  215,  222,  359,  359,
      359,  192,  142,  191,  225,  239,  227,  228,  246,    0,
      233,    0,    0,  225,  232,  222,  228,    0,    0,  223,
      219,    0,  219,  219,  215,  226,  216,    0,  224,  359,
      359,    0,    0,  214,  213,  217,  208,    0,  203,  206,

        0,  213,  209,    0,  193,  151,    0,    0,  142,    0,
        0,    0,  135,    0,   39,    0,    0,  359,  280,  283,
      285,  288,  291,   82,  294,  297,  300,  303
    } ;

static yyconst short int yy_def[229] =
    {   0,
      218,    1,  218,  218,  218,  218,  218,  219,  218,  218,
      220,  218,  218,  218,  218,  218,  218,  218,  218,  218,
       20,  218,  218,  218,  218,  218,  218,  221,  221,  218,
      218,  218,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  218,  218,  218,  218,  218,  218,
      219,  218,  222,  218,  218,  218,  218,  220,  218,  223,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,   21,  218,  218,  218,  224,  218,  218,  218,
      218,  218,  218,  218,  218,  221,  225,  226,  218,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  218,
      218,  219,  219,  222,  220,  220,  223,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  224,  218,  218,  225,
      218,  227,  226,  218,  228,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  218,  218,  218,  218,
      218,  218,  218,  225,  225,  227,  226,  226,  228,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  218,
      218,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,    0,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218
    } ;

static yyconst short int yy_nxt[422] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   29,
       28,   28,   30,    4,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   28,   40,   28,   28,   28,   28,   28,
       41,   42,   28,   28,   43,   44,   28,   28,   45,   46,
       47,   48,   52,   54,   55,   56,   59,   62,   79,   67,
       64,   68,   68,   68,   69,   73,   73,  110,   63,   65,
       66,   57,   80,  127,   81,   82,   70,   84,   85,  217,
      218,   53,   60,   71,   95,   72,   72,   73,   87,   92,

       52,   88,   59,   96,  100,   74,   93,  101,   75,   76,
       77,   97,   94,   98,  111,  218,  103,  106,  107,   74,
       51,   99,  113,  104,  126,   75,   58,  125,   60,   53,
      131,  116,   76,  153,   52,   77,   68,   68,   68,  134,
       52,  126,  150,   68,   68,   68,  119,  120,  154,  120,
      125,  114,  151,  119,  120,   59,  120,  117,   59,  132,
      119,  120,  160,   53,  159,  135,  120,  119,  120,   53,
       51,  191,  113,  120,   71,  216,   72,   72,   73,  160,
       58,   60,  215,  131,   60,  116,   74,  159,  191,  121,
      122,  123,  130,  123,  165,  131,  124,  124,  124,  134,

       74,  114,  157,  214,  157,  133,  121,  158,  158,  158,
      168,  117,  132,  122,  124,  124,  124,  124,  124,  124,
      162,  163,  190,  166,  132,  135,  174,  175,  161,  131,
      161,  158,  158,  158,  134,  134,  169,  162,  158,  158,
      158,  130,  161,  165,  163,  190,  213,  161,  133,  120,
      212,  120,  211,  168,  210,  209,  208,  207,  132,  206,
      135,  135,  205,  120,  204,  203,  202,  201,  120,  200,
      199,  198,  166,  197,  196,  195,  194,  193,  192,  169,
       51,   51,   51,   58,   58,   58,   86,   86,  112,  112,
      112,  115,  115,  115,  130,  130,  130,  133,  133,  133,

      164,  164,  164,  167,  167,  167,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      173,  172,  171,  170,  156,  155,  152,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
      136,  129,  128,  118,   49,  109,  108,  105,  102,   91,
       90,   89,   83,   78,   61,   50,   49,  218,    3,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218
    } ;

static yyconst short int yy_chk[422] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,    9,    9,   10,   11,   15,   24,   18,
       17,   18,   18,   18,   19,   21,   21,   46,   15,   17,
       17,   10,   24,  224,   24,   24,   19,   26,   26,  215,
       21,    8,   11,   20,   36,   20,   20,   20,   29,   35,

       51,   29,   58,   36,   38,   20,   35,   38,   20,   20,
       20,   37,   35,   37,   46,   21,   40,   42,   42,   20,
       53,   37,   53,   40,   76,   20,   60,   75,   58,   51,
       87,   60,   20,  107,  112,   20,   68,   68,   68,   88,
      113,   76,  105,   71,   71,   71,   68,   68,  107,   68,
       75,   53,  105,   71,   71,  115,   71,   60,  116,   87,
       68,   68,  122,  112,  121,   88,   68,   71,   71,  113,
      114,  163,  114,   71,   72,  213,   72,   72,   72,  122,
      117,  115,  209,  130,  116,  117,   72,  121,  163,   72,
       72,   74,  132,   74,  132,  164,   74,   74,   74,  133,

       72,  114,  119,  206,  119,  135,   72,  119,  119,  119,
      135,  117,  130,   72,  123,  123,  123,  124,  124,  124,
      127,  127,  162,  132,  164,  133,  140,  140,  124,  165,
      124,  157,  157,  157,  167,  168,  135,  127,  158,  158,
      158,  166,  124,  166,  127,  162,  205,  124,  169,  158,
      203,  158,  202,  169,  200,  199,  197,  196,  165,  195,
      167,  168,  194,  158,  189,  187,  186,  185,  158,  184,
      183,  181,  166,  180,  177,  176,  175,  174,  171,  169,
      219,  219,  219,  220,  220,  220,  221,  221,  222,  222,
      222,  223,  223,  223,  225,  225,  225,  226,  226,  226,

      227,  227,  227,  228,  228,  228,  156,  155,  154,  153,
      152,  151,  150,  148,  146,  145,  144,  143,  142,  141,
      139,  138,  137,  136,  109,  108,  106,  104,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   85,   81,   67,   49,   44,   43,   41,   39,   34,
       33,   32,   25,   22,   14,    7,    5,    3,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
/*	$Id: lexer.l,v 1.3 1997/11/22 18:41:23 sandro Exp $	*/
/*
 * Copyright (c) 1997 Sandro Sigala <ssigala@globalnet.it>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ISO C lexical analyzer.
 *
 * Based on the ISO C 9899:1990 international standard.
 */
#line 35 "lexer.l"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include <assert.h>
#include <stdlib.h>

#include "symtable.h"
#include "symbols.h"
#include "parser.tab.h"

extern	symtableQ_t	*g_SymbolTable;

extern	yystype			yylval;

int lineno;

static int yywrap(void);
static void skip_comment(void);
static int check_identifier(const char *);
#line 583 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 64 "lexer.l"


#line 737 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 359 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "lexer.l"
{ ++lineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "lexer.l"
{ /* Ignore whitespace. */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "lexer.l"
{ skip_comment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 71 "lexer.l"
{ return '{'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "lexer.l"
{ return '{'; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "lexer.l"
{ return '}'; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 74 "lexer.l"
{ return '}'; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 75 "lexer.l"
{ return '['; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return '['; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return ']'; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return ']'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "lexer.l"
{ return '('; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 80 "lexer.l"
{ return ')'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 81 "lexer.l"
{ return ';'; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return ':'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return ELLIPSIS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return '?'; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return '.'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return '+'; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return '-'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return '*'; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return '/'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return '%'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return '^'; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return '&'; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return '|'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return '~'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return '!'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return '='; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return '<'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return '>'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return ADDEQ; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return SUBEQ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return MULEQ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return DIVEQ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return MODEQ; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return XOREQ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return ANDEQ; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return OREQ; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return SL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return SR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return SLEQ; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return SREQ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return EQ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return NOTEQ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return LTEQ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return GTEQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return ANDAND; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return OROR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return PLUSPLUS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return MINUSMINUS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return ','; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return ARROW; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return AUTO; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return BREAK; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return CASE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "lexer.l"
{ yylval.decl_type = CHAR; return CHAR; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return CONST; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return CONTINUE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return DEFAULT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return DO; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return DOUBLE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return ELSE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return ENUM; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return EXTERN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return FLOAT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return FOR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return IF; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "lexer.l"
{ yylval.decl_type = INT; return INT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return REGISTER; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return RETURN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return SHORT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return SIGNED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return SIZEOF; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "lexer.l"
{ yylval.decl_type = VOID; return VOID; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return WHILE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return GOTO; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return check_identifier(yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 148 "lexer.l"
{ symtableentry_t *pEntry = create_symbol_table_entry(); 
														pEntry->ident_ptr.ident_type = IDENT_DEF_CONSTANT_INT;
														pEntry->ident_ptr.ident_info.const_int = atoi(yytext);

														yylval.pEntry	=	pEntry;
														return INTEGER; 
														}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 155 "lexer.l"
{ 
													symtableentry_t *pEntry = create_symbol_table_entry(); 
														pEntry->ident_ptr.ident_type = IDENT_DEF_CONSTANT_INT;
														pEntry->ident_ptr.ident_info.const_int = atoi(yytext);

														yylval.pEntry	=	pEntry;
													return INTEGER; 
												}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 163 "lexer.l"
{ 
													symtableentry_t *pEntry = create_symbol_table_entry(); 
														pEntry->ident_ptr.ident_type = IDENT_DEF_CONSTANT_INT;
														pEntry->ident_ptr.ident_info.const_int = atoi(yytext);

														yylval.pEntry	=	pEntry;
													return INTEGER; 
									}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return FLOATING; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return FLOATING; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return CHARACTER; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 176 "lexer.l"
{ return CHARACTER; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 178 "lexer.l"
{ return STRING; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 179 "lexer.l"
{ return STRING; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 181 "lexer.l"
{ fprintf(stderr, "%d: unexpected character `%c'\n", lineno, yytext[0]); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 183 "lexer.l"
ECHO;
	YY_BREAK
#line 1285 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 218);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 183 "lexer.l"


static int
yywrap(void)
{
	return 1;
}

/*
 * We use this routine instead a lex pattern because we don't need
 * to save the matched comment in the `yytext' buffer.
 */
static void
skip_comment(void)
{
	int c1, c2;

	c1 = input();
	c2 = input();

	while (c2 != EOF && !(c1 == '*' && c2 == '/')) {
		if (c1 == '\n')
			++lineno;
		c1 = c2;
		c2 = input();
	}
}

static int
check_identifier(const char *s)
{
	/*
	 * This function should check if `s' is a type name or an
	 * identifier.
	 */

	 symtableentry_t	*p_entry;

	 p_entry = get_ident_entry(s);

	 if ( NULL == p_entry )
	 {
		p_entry = create_symbol_table_entry();

		p_entry->p_next	=	NULL;
		p_entry->id_name	=	strdup(s);
	 }

	 assert(p_entry);

	 yylval.pEntry	=	p_entry;

	return IDENTIFIER;
}