package com.deitel.advjhtp1.idl.domain;


/**
* com/deitel/advjhtp1/idl/domain/CustomerHome.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from domain.idl
* Sunday, July 1, 2001 11:46:27 PM PDT
*/

public interface CustomerHome extends CustomerHomeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CustomerHome
