package com.deitel.advjhtp1.idl.domain;


/**
* com/deitel/advjhtp1/idl/domain/DatabaseExceptionHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from domain.idl
* Sunday, July 1, 2001 11:46:27 PM PDT
*/

abstract public class DatabaseExceptionHelper
{
  private static String  _id = "IDL:domain/DatabaseException:1.0";

  public static void insert (org.omg.CORBA.Any a, com.deitel.advjhtp1.idl.domain.DatabaseException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.deitel.advjhtp1.idl.domain.DatabaseException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "msg",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.deitel.advjhtp1.idl.domain.DatabaseExceptionHelper.id (), "DatabaseException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.deitel.advjhtp1.idl.domain.DatabaseException read (org.omg.CORBA.portable.InputStream istream)
  {
    com.deitel.advjhtp1.idl.domain.DatabaseException value = new com.deitel.advjhtp1.idl.domain.DatabaseException ();
    // read and discard the repository ID
    istream.read_string ();
    value.msg = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.deitel.advjhtp1.idl.domain.DatabaseException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_string (value.msg);
  }

}
