package com.deitel.messenger.obvcorba.server;


/**
* com/deitel/messenger/obvcorba/server/_StoppableChatServerImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:45 PM EDT
*/

public abstract class _StoppableChatServerImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements com.deitel.messenger.obvcorba.server.StoppableChatServer, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _StoppableChatServerImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("stopServer", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // obvcorba/server/StoppableChatServer/stopServer
       {
         this.stopServer ();
         out = rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:obvcorba/server/StoppableChatServer:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _StoppableChatServerImplBase
