package com.deitel.messenger.obvcorba;

/**
* com/deitel/messenger/obvcorba/ChatMessageHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:45 PM EDT
*/

public final class ChatMessageHolder implements org.omg.CORBA.portable.Streamable
{
  public com.deitel.messenger.obvcorba.ChatMessage value = null;

  public ChatMessageHolder ()
  {
  }

  public ChatMessageHolder (com.deitel.messenger.obvcorba.ChatMessage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.deitel.messenger.obvcorba.ChatMessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.deitel.messenger.obvcorba.ChatMessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.deitel.messenger.obvcorba.ChatMessageHelper.type ();
  }

}
