package com.deitel.messenger.obvcorba.server;


/**
* com/deitel/messenger/obvcorba/server/ChatServiceOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:46 PM EDT
*/


// Create a combination interface
public interface ChatServiceOperations  extends com.deitel.messenger.obvcorba.server.ChatServerOperations, com.deitel.messenger.obvcorba.server.StoppableChatServerOperations
{
} // interface ChatServiceOperations
