package com.deitel.messenger.obvcorba.server;


/**
* com/deitel/messenger/obvcorba/server/ChatServiceHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:46 PM EDT
*/


// Create a combination interface
abstract public class ChatServiceHelper
{
  private static String  _id = "IDL:obvcorba/server/ChatService:1.0";

  public static void insert (org.omg.CORBA.Any a, com.deitel.messenger.obvcorba.server.ChatService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.deitel.messenger.obvcorba.server.ChatService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.deitel.messenger.obvcorba.server.ChatServiceHelper.id (), "ChatService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.deitel.messenger.obvcorba.server.ChatService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ChatServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.deitel.messenger.obvcorba.server.ChatService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.deitel.messenger.obvcorba.server.ChatService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.deitel.messenger.obvcorba.server.ChatService)
      return (com.deitel.messenger.obvcorba.server.ChatService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new com.deitel.messenger.obvcorba.server._ChatServiceStub (delegate);
    }
  }

}
