package com.deitel.messenger.obvcorba;


/**
* com/deitel/messenger/obvcorba/ChatMessageDefaultFactory.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:45 PM EDT
*/

public class ChatMessageDefaultFactory implements ChatMessageValueFactory {

  public ChatMessage create (String from, String message)
  {
    return new ChatMessageImpl (from, message);
  }

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new ChatMessageImpl ());
  }
}
