package com.deitel.messenger.obvcorba.client;

/**
* com/deitel/messenger/obvcorba/client/ChatClientHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:45 PM EDT
*/

public final class ChatClientHolder implements org.omg.CORBA.portable.Streamable
{
  public com.deitel.messenger.obvcorba.client.ChatClient value = null;

  public ChatClientHolder ()
  {
  }

  public ChatClientHolder (com.deitel.messenger.obvcorba.client.ChatClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.deitel.messenger.obvcorba.client.ChatClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.deitel.messenger.obvcorba.client.ChatClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.deitel.messenger.obvcorba.client.ChatClientHelper.type ();
  }

}
