package com.deitel.messenger.obvcorba.server;

/**
* com/deitel/messenger/obvcorba/server/StoppableChatServerHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:45 PM EDT
*/

public final class StoppableChatServerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.deitel.messenger.obvcorba.server.StoppableChatServer value = null;

  public StoppableChatServerHolder ()
  {
  }

  public StoppableChatServerHolder (com.deitel.messenger.obvcorba.server.StoppableChatServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.deitel.messenger.obvcorba.server.StoppableChatServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.deitel.messenger.obvcorba.server.StoppableChatServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.deitel.messenger.obvcorba.server.StoppableChatServerHelper.type ();
  }

}
