package com.deitel.messenger.obvcorba.server;


/**
* com/deitel/messenger/obvcorba/server/StoppableChatServer.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 10:20:45 PM EDT
*/

public interface StoppableChatServer extends StoppableChatServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StoppableChatServer
