/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIPIWrapper */

#ifndef _Included_JNIPIWrapper
#define _Included_JNIPIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIPIWrapper
 * Method:    getPI
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_JNIPIWrapper_getPI__
  (JNIEnv *, jobject);

/*
 * Class:     JNIPIWrapper
 * Method:    getPI
 * Signature: (LPIContainer;)D
 */
JNIEXPORT jdouble JNICALL Java_JNIPIWrapper_getPI__LPIContainer_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
