/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITintWrapper */

#ifndef _Included_JNITintWrapper
#define _Included_JNITintWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITintWrapper
 * Method:    tintImage
 * Signature: ([IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_JNITintWrapper_tintImage
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
