package com.deitel.advjhtp1.idl.dii;


/**
* com/deitel/advjhtp1/idl/dii/SystemClockOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from systemclock.idl
* Monday, July 2, 2001 1:44:02 AM PDT
*/

public interface SystemClockOperations 
{
  long currentTimeMillis ();
} // interface SystemClockOperations
