package maptest;


/**
* maptest/_InterfaceNameImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from maptest.idl
* Monday, May 14, 2001 4:18:09 PM PDT
*/


// the interface declaration for InterfaceName
public abstract class _InterfaceNameImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements maptest.InterfaceName, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _InterfaceNameImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_anAttribute", new java.lang.Integer (0));
    _methods.put ("_set_anAttribute", new java.lang.Integer (1));
    _methods.put ("_get_roAttribute", new java.lang.Integer (2));
    _methods.put ("seqMethod", new java.lang.Integer (3));
    _methods.put ("boundSeqMethod", new java.lang.Integer (4));
    _methods.put ("arrayMethod", new java.lang.Integer (5));
    _methods.put ("intOutMethod", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // comment above the readwrite attribute
       case 0:  // maptest/InterfaceName/_get_anAttribute
       {
         int __result = (int)0;
         __result = this.anAttribute ();
         out = rh.createReply();
         out.write_long (__result);
         break;
       }


  // comment above the readwrite attribute
       case 1:  // maptest/InterfaceName/_set_anAttribute
       {
         int newAnAttribute = in.read_long ();
         this.anAttribute (newAnAttribute);
         out = rh.createReply();
         break;
       }

       case 2:  // maptest/InterfaceName/_get_roAttribute
       {
         int __result = (int)0;
         __result = this.roAttribute ();
         out = rh.createReply();
         out.write_long (__result);
         break;
       }


  // comment above our methods
       case 3:  // maptest/InterfaceName/seqMethod
       {
         maptest.StructMap seq[] = maptest.StructMapSeqHelper.read (in);
         this.seqMethod (seq);
         out = rh.createReply();
         break;
       }

       case 4:  // maptest/InterfaceName/boundSeqMethod
       {
         maptest.StructMap seq[] = maptest.BoundStructMapSeqHelper.read (in);
         this.boundSeqMethod (seq);
         out = rh.createReply();
         break;
       }

       case 5:  // maptest/InterfaceName/arrayMethod
       {
         int array[] = maptest.IntArrayHelper.read (in);
         this.arrayMethod (array);
         out = rh.createReply();
         break;
       }

       case 6:  // maptest/InterfaceName/intOutMethod
       {
         org.omg.CORBA.IntHolder intValue = new org.omg.CORBA.IntHolder ();
         intValue.value = in.read_long ();
         this.intOutMethod (intValue);
         out = rh.createReply();
         out.write_long (intValue.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:maptest/InterfaceName:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _InterfaceNameImplBase
