package maptest;


/**
* maptest/InterfaceName.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from maptest.idl
* Monday, May 14, 2001 4:18:09 PM PDT
*/


// the interface declaration for InterfaceName
public interface InterfaceName extends InterfaceNameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final int constantValue = (int)(42);
} // interface InterfaceName
