package maptest;


/**
* maptest/InterfaceNameOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from maptest.idl
* Monday, May 14, 2001 4:18:09 PM PDT
*/


// the interface declaration for InterfaceName
public interface InterfaceNameOperations 
{

  // comment above the readwrite attribute
  int anAttribute ();

  // comment above the readwrite attribute
  void anAttribute (int newAnAttribute);
  int roAttribute ();

  // comment above our methods
  void seqMethod (maptest.StructMap[] seq);
  void boundSeqMethod (maptest.StructMap[] seq);
  void arrayMethod (int[] array);
  void intOutMethod (org.omg.CORBA.IntHolder intValue);
} // interface InterfaceNameOperations
