package maptest;


/**
* maptest/StructMap.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from maptest.idl
* Monday, May 14, 2001 4:18:09 PM PDT
*/


// This comment appears in the generated files for StructMap
public final class StructMap implements
   org.omg.CORBA.portable.IDLEntity
{

   // This comment appears at the start of the type declarations
   public boolean boolValue = false;
   public char charValue = (char)0;
   public char wCharValue = (char)0;
   public byte octetValue = (byte)0;
   public String stringValue = null;
   public String wStringValue = null;
   public short shortValue = (short)0;
   public short uShortValue = (short)0;
   public int longValue = (int)0;
   public int uLongValue = (int)0;
   public long longLongValue = (long)0;
   public long uLongLongValue = (long)0;
   public float floatValue = (float)0;
   public double doubleValue = (double)0;

   public StructMap ()
   {
   } // ctor

   public StructMap (boolean _boolValue, char _charValue,
      char _wCharValue, byte _octetValue, String _stringValue,
      String _wStringValue, short _shortValue,
      short _uShortValue, int _longValue, int _uLongValue,
      long _longLongValue, long _uLongLongValue,
      float _floatValue, double _doubleValue)
   {
      boolValue = _boolValue;
      charValue = _charValue;
      wCharValue = _wCharValue;
      octetValue = _octetValue;
      stringValue = _stringValue;
      wStringValue = _wStringValue;
      shortValue = _shortValue;
      uShortValue = _uShortValue;
      longValue = _longValue;
      uLongValue = _uLongValue;
      longLongValue = _longLongValue;
      uLongLongValue = _uLongLongValue;
      floatValue = _floatValue;
      doubleValue = _doubleValue;
   } // ctor

} // class StructMap
