'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3512.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsDoctors
    Inherits DataSet
    
    Private tabledoctors As doctorsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("doctors")) Is Nothing) Then
                Me.Tables.Add(New doctorsDataTable(ds.Tables("doctors")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property doctors As doctorsDataTable
        Get
            Return Me.tabledoctors
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsDoctors = CType(MyBase.Clone,dsDoctors)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("doctors")) Is Nothing) Then
            Me.Tables.Add(New doctorsDataTable(ds.Tables("doctors")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tabledoctors = CType(Me.Tables("doctors"),doctorsDataTable)
        If (Not (Me.tabledoctors) Is Nothing) Then
            Me.tabledoctors.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsDoctors"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsDoctors.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tabledoctors = New doctorsDataTable
        Me.Tables.Add(Me.tabledoctors)
    End Sub
    
    Private Function ShouldSerializedoctors() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub doctorsRowChangeEventHandler(ByVal sender As Object, ByVal e As doctorsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class doctorsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columndr_id As DataColumn
        
        Private columndr_lname As DataColumn
        
        Private columndr_fname As DataColumn
        
        Private columnphone As DataColumn
        
        Private columnaddress As DataColumn
        
        Private columncity As DataColumn
        
        Private columnstate As DataColumn
        
        Private columnzip As DataColumn
        
        Friend Sub New()
            MyBase.New("doctors")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property dr_idColumn As DataColumn
            Get
                Return Me.columndr_id
            End Get
        End Property
        
        Friend ReadOnly Property dr_lnameColumn As DataColumn
            Get
                Return Me.columndr_lname
            End Get
        End Property
        
        Friend ReadOnly Property dr_fnameColumn As DataColumn
            Get
                Return Me.columndr_fname
            End Get
        End Property
        
        Friend ReadOnly Property phoneColumn As DataColumn
            Get
                Return Me.columnphone
            End Get
        End Property
        
        Friend ReadOnly Property addressColumn As DataColumn
            Get
                Return Me.columnaddress
            End Get
        End Property
        
        Friend ReadOnly Property cityColumn As DataColumn
            Get
                Return Me.columncity
            End Get
        End Property
        
        Friend ReadOnly Property stateColumn As DataColumn
            Get
                Return Me.columnstate
            End Get
        End Property
        
        Friend ReadOnly Property zipColumn As DataColumn
            Get
                Return Me.columnzip
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As doctorsRow
            Get
                Return CType(Me.Rows(index),doctorsRow)
            End Get
        End Property
        
        Public Event doctorsRowChanged As doctorsRowChangeEventHandler
        
        Public Event doctorsRowChanging As doctorsRowChangeEventHandler
        
        Public Event doctorsRowDeleted As doctorsRowChangeEventHandler
        
        Public Event doctorsRowDeleting As doctorsRowChangeEventHandler
        
        Public Overloads Sub AdddoctorsRow(ByVal row As doctorsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AdddoctorsRow(ByVal dr_id As String, ByVal dr_lname As String, ByVal dr_fname As String, ByVal phone As String, ByVal address As String, ByVal city As String, ByVal state As String, ByVal zip As String) As doctorsRow
            Dim rowdoctorsRow As doctorsRow = CType(Me.NewRow,doctorsRow)
            rowdoctorsRow.ItemArray = New Object() {dr_id, dr_lname, dr_fname, phone, address, city, state, zip}
            Me.Rows.Add(rowdoctorsRow)
            Return rowdoctorsRow
        End Function
        
        Public Function FindBydr_id(ByVal dr_id As String) As doctorsRow
            Return CType(Me.Rows.Find(New Object() {dr_id}),doctorsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As doctorsDataTable = CType(MyBase.Clone,doctorsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Friend Sub InitVars()
            Me.columndr_id = Me.Columns("dr_id")
            Me.columndr_lname = Me.Columns("dr_lname")
            Me.columndr_fname = Me.Columns("dr_fname")
            Me.columnphone = Me.Columns("phone")
            Me.columnaddress = Me.Columns("address")
            Me.columncity = Me.Columns("city")
            Me.columnstate = Me.Columns("state")
            Me.columnzip = Me.Columns("zip")
        End Sub
        
        Private Sub InitClass()
            Me.columndr_id = New DataColumn("dr_id", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndr_id)
            Me.columndr_lname = New DataColumn("dr_lname", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndr_lname)
            Me.columndr_fname = New DataColumn("dr_fname", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndr_fname)
            Me.columnphone = New DataColumn("phone", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnphone)
            Me.columnaddress = New DataColumn("address", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnaddress)
            Me.columncity = New DataColumn("city", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncity)
            Me.columnstate = New DataColumn("state", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnstate)
            Me.columnzip = New DataColumn("zip", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnzip)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columndr_id}, true))
            Me.columndr_id.AllowDBNull = false
            Me.columndr_id.Unique = true
            Me.columndr_lname.AllowDBNull = false
            Me.columndr_fname.AllowDBNull = false
        End Sub
        
        Public Function NewdoctorsRow() As doctorsRow
            Return CType(Me.NewRow,doctorsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New doctorsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(doctorsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.doctorsRowChangedEvent) Is Nothing) Then
                RaiseEvent doctorsRowChanged(Me, New doctorsRowChangeEvent(CType(e.Row,doctorsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.doctorsRowChangingEvent) Is Nothing) Then
                RaiseEvent doctorsRowChanging(Me, New doctorsRowChangeEvent(CType(e.Row,doctorsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.doctorsRowDeletedEvent) Is Nothing) Then
                RaiseEvent doctorsRowDeleted(Me, New doctorsRowChangeEvent(CType(e.Row,doctorsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.doctorsRowDeletingEvent) Is Nothing) Then
                RaiseEvent doctorsRowDeleting(Me, New doctorsRowChangeEvent(CType(e.Row,doctorsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovedoctorsRow(ByVal row As doctorsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class doctorsRow
        Inherits DataRow
        
        Private tabledoctors As doctorsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tabledoctors = CType(Me.Table,doctorsDataTable)
        End Sub
        
        Public Property dr_id As String
            Get
                Return CType(Me(Me.tabledoctors.dr_idColumn),String)
            End Get
            Set
                Me(Me.tabledoctors.dr_idColumn) = value
            End Set
        End Property
        
        Public Property dr_lname As String
            Get
                Return CType(Me(Me.tabledoctors.dr_lnameColumn),String)
            End Get
            Set
                Me(Me.tabledoctors.dr_lnameColumn) = value
            End Set
        End Property
        
        Public Property dr_fname As String
            Get
                Return CType(Me(Me.tabledoctors.dr_fnameColumn),String)
            End Get
            Set
                Me(Me.tabledoctors.dr_fnameColumn) = value
            End Set
        End Property
        
        Public Property phone As String
            Get
                Try 
                    Return CType(Me(Me.tabledoctors.phoneColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledoctors.phoneColumn) = value
            End Set
        End Property
        
        Public Property address As String
            Get
                Try 
                    Return CType(Me(Me.tabledoctors.addressColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledoctors.addressColumn) = value
            End Set
        End Property
        
        Public Property city As String
            Get
                Try 
                    Return CType(Me(Me.tabledoctors.cityColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledoctors.cityColumn) = value
            End Set
        End Property
        
        Public Property state As String
            Get
                Try 
                    Return CType(Me(Me.tabledoctors.stateColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledoctors.stateColumn) = value
            End Set
        End Property
        
        Public Property zip As String
            Get
                Try 
                    Return CType(Me(Me.tabledoctors.zipColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledoctors.zipColumn) = value
            End Set
        End Property
        
        Public Function IsphoneNull() As Boolean
            Return Me.IsNull(Me.tabledoctors.phoneColumn)
        End Function
        
        Public Sub SetphoneNull()
            Me(Me.tabledoctors.phoneColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsaddressNull() As Boolean
            Return Me.IsNull(Me.tabledoctors.addressColumn)
        End Function
        
        Public Sub SetaddressNull()
            Me(Me.tabledoctors.addressColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IscityNull() As Boolean
            Return Me.IsNull(Me.tabledoctors.cityColumn)
        End Function
        
        Public Sub SetcityNull()
            Me(Me.tabledoctors.cityColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsstateNull() As Boolean
            Return Me.IsNull(Me.tabledoctors.stateColumn)
        End Function
        
        Public Sub SetstateNull()
            Me(Me.tabledoctors.stateColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IszipNull() As Boolean
            Return Me.IsNull(Me.tabledoctors.zipColumn)
        End Function
        
        Public Sub SetzipNull()
            Me(Me.tabledoctors.zipColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class doctorsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As doctorsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As doctorsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As doctorsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
