package com.deitel.messenger.corba.server;


/**
* com/deitel/messenger/corba/server/ChatServiceOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 6:24:11 PM EDT
*/


// Create a combination interface
public interface ChatServiceOperations  extends com.deitel.messenger.corba.server.ChatServerOperations, com.deitel.messenger.corba.server.StoppableChatServerOperations
{
} // interface ChatServiceOperations
