package com.deitel.messenger.corba.server;


/**
* com/deitel/messenger/corba/server/ChatServerOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from chat.idl
* Tuesday, August 21, 2001 6:24:10 PM EDT
*/

public interface ChatServerOperations 
{

  // register new ChatClient with ChatServer
  void registerClient (com.deitel.messenger.corba.client.ChatClient client);

  // unregister ChatClient with ChatServer
  void unregisterClient (com.deitel.messenger.corba.client.ChatClient client);

  // post new message to ChatServer
  void postMessage (com.deitel.messenger.corba.ChatMessage message);
} // interface ChatServerOperations
