package com.deitel.advjhtp1.idl.clock;


/**
* com/deitel/advjhtp1/idl/clock/SystemClock.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from systemclock.idl
* Sunday, July 1, 2001 10:36:53 PM PDT
*/


// The definition of the CORBA-enabled service
public interface SystemClock extends SystemClockOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SystemClock
