//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace ASPNetCS.WeatherWebRef {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WeatherServiceSoap", Namespace="http://tempuri.org/")]
    public class WeatherService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WeatherService() {
            this.Url = "http://localhost/CSTASPNET/democode/Mod13CS/WeatherService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WeatherByCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WeatherByCity(string City) {
            object[] results = this.Invoke("WeatherByCity", new object[] {
                        City});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWeatherByCity(string City, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WeatherByCity", new object[] {
                        City}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndWeatherByCity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TemperatureByCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int TemperatureByCity(string City) {
            object[] results = this.Invoke("TemperatureByCity", new object[] {
                        City});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTemperatureByCity(string City, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TemperatureByCity", new object[] {
                        City}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndTemperatureByCity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TravelAdviceByCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TravelAdviceByCity(string City) {
            object[] results = this.Invoke("TravelAdviceByCity", new object[] {
                        City});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTravelAdviceByCity(string City, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TravelAdviceByCity", new object[] {
                        City}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTravelAdviceByCity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
