package com.deitel.advjhtp1.idl.alarm;


/**
* com/deitel/advjhtp1/idl/alarm/_AlarmClockStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from alarmclock2.idl
* Sunday, July 1, 2001 11:48:22 PM PDT
*/

public class _AlarmClockStub extends org.omg.CORBA.portable.ObjectImpl implements com.deitel.advjhtp1.idl.alarm.AlarmClock
{
  // Constructors
  // NOTE:  If the default constructor is used, the
  //        object is useless until _set_delegate (...)
  //        is called.
  public _AlarmClockStub ()
  {
    super ();
  }

  public _AlarmClockStub (org.omg.CORBA.portable.Delegate delegate)
  {
    super ();
    _set_delegate (delegate);
  }

  public void addAlarmListener (String listenerName, com.deitel.advjhtp1.idl.alarm.AlarmListener listener) throws com.deitel.advjhtp1.idl.alarm.DuplicateNameException
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("addAlarmListener", true);
       _out.write_string (listenerName);
       com.deitel.advjhtp1.idl.alarm.AlarmListenerHelper.write (_out, listener);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       if (_id.equals ("IDL:alarm/DuplicateNameException:1.0"))
          throw com.deitel.advjhtp1.idl.alarm.DuplicateNameExceptionHelper.read (_in);
       else
            throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       addAlarmListener (listenerName, listener);
    } finally {
        _releaseReply (_in);
    }
  } // addAlarmListener

  public void setAlarm (String listenerName, long seconds)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("setAlarm", true);
       _out.write_string (listenerName);
       _out.write_longlong (seconds);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       setAlarm (listenerName, seconds);
    } finally {
        _releaseReply (_in);
    }
  } // setAlarm

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:alarm/AlarmClock:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s)
  {
     try 
     {
       String str = s.readUTF ();
       org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init ().string_to_object (str);
       org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
       _set_delegate (delegate);
     } catch (java.io.IOException e) {}
  }

  private void writeObject (java.io.ObjectOutputStream s)
  {
     try 
     {
       String str = org.omg.CORBA.ORB.init ().object_to_string (this);
       s.writeUTF (str);
     } catch (java.io.IOException e) {}
  }
} // class _AlarmClockStub
