package com.deitel.advjhtp1.idl.alarm;


/**
* com/deitel/advjhtp1/idl/alarm/_AlarmListenerImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from alarmclock2.idl
* Sunday, July 1, 2001 11:48:22 PM PDT
*/

public abstract class _AlarmListenerImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements com.deitel.advjhtp1.idl.alarm.AlarmListener, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AlarmListenerImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateTime", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // alarm/AlarmListener/updateTime
       {
         long newTime = in.read_longlong ();
         this.updateTime (newTime);
         out = rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:alarm/AlarmListener:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _AlarmListenerImplBase
