package com.deitel.advjhtp1.idl.alarm;


/**
* com/deitel/advjhtp1/idl/alarm/AlarmListenerHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from alarmclock2.idl
* Sunday, July 1, 2001 11:48:22 PM PDT
*/

abstract public class AlarmListenerHelper
{
  private static String  _id = "IDL:alarm/AlarmListener:1.0";

  public static void insert (org.omg.CORBA.Any a, com.deitel.advjhtp1.idl.alarm.AlarmListener that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.deitel.advjhtp1.idl.alarm.AlarmListener extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.deitel.advjhtp1.idl.alarm.AlarmListenerHelper.id (), "AlarmListener");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.deitel.advjhtp1.idl.alarm.AlarmListener read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AlarmListenerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.deitel.advjhtp1.idl.alarm.AlarmListener value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.deitel.advjhtp1.idl.alarm.AlarmListener narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.deitel.advjhtp1.idl.alarm.AlarmListener)
      return (com.deitel.advjhtp1.idl.alarm.AlarmListener)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new com.deitel.advjhtp1.idl.alarm._AlarmListenerStub (delegate);
    }
  }

}
