package com.deitel.advjhtp1.idl.alarm;

/**
* com/deitel/advjhtp1/idl/alarm/AlarmListenerHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from alarmclock2.idl
* Sunday, July 1, 2001 11:48:22 PM PDT
*/

public final class AlarmListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.deitel.advjhtp1.idl.alarm.AlarmListener value = null;

  public AlarmListenerHolder ()
  {
  }

  public AlarmListenerHolder (com.deitel.advjhtp1.idl.alarm.AlarmListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.deitel.advjhtp1.idl.alarm.AlarmListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.deitel.advjhtp1.idl.alarm.AlarmListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.deitel.advjhtp1.idl.alarm.AlarmListenerHelper.type ();
  }

}
