package com.deitel.advjhtp1.idl.alarm;

/**
* com/deitel/advjhtp1/idl/alarm/DuplicateNameExceptionHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from alarmclock2.idl
* Sunday, July 1, 2001 11:48:22 PM PDT
*/

public final class DuplicateNameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.deitel.advjhtp1.idl.alarm.DuplicateNameException value = null;

  public DuplicateNameExceptionHolder ()
  {
  }

  public DuplicateNameExceptionHolder (com.deitel.advjhtp1.idl.alarm.DuplicateNameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.deitel.advjhtp1.idl.alarm.DuplicateNameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.deitel.advjhtp1.idl.alarm.DuplicateNameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.deitel.advjhtp1.idl.alarm.DuplicateNameExceptionHelper.type ();
  }

}
