package com.deitel.advjhtp1.idl.alarm;


/**
* com/deitel/advjhtp1/idl/alarm/DuplicateNameException.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from alarmclock2.idl
* Sunday, July 1, 2001 11:48:22 PM PDT
*/

public final class DuplicateNameException extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public String msg = null;

  public DuplicateNameException ()
  {
  } // ctor

  public DuplicateNameException (String _msg)
  {
    msg = _msg;
  } // ctor

} // class DuplicateNameException
