/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIStaticWrapper */

#ifndef _Included_JNIStaticWrapper
#define _Included_JNIStaticWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIStaticWrapper
 * Method:    printStaticMembers
 * Signature: (LMathConstants;)V
 */
JNIEXPORT void JNICALL Java_JNIStaticWrapper_printStaticMembers
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
